# Generated by Django 4.2 on 2023-04-17 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_payment_orderplaced'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='stripe_order_id',
            new_name='razorpay_order_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='stripe_payment_id',
            new_name='razorpay_payment_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='stripe_payment_status',
            new_name='razorpay_payment_status',
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('On The Way', 'On The Way'), ('Cancelled', 'Cancelled'), ('Packed', 'Packed'), ('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Accepted', 'Accepted')], default='Pending', max_length=50),
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
