# Generated by Django 4.2 on 2023-04-18 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_order_remove_payment_user_delete_orderplaced_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='is_payed',
            new_name='is_paid',
        ),
    ]
